homepage:
  path: /
  defaults: { _controller: HikingBundle:Hiking:showTracks }

all_tracks:
  path: /tracks
  defaults: { _controller: HikingBundle:Hiking:showTracks }

single_track:
  path: /track/{track_id}
  defaults: { _controller: HikingBundle:Hiking:showSingleTrack }
  requirements:
    track_id: \d+

single_member:
  path: /member/{member_id}
  defaults: { _controller: HikingBundle:Hiking:showSingleMember }
  requirements:
    member_id: \d+


