homepage:
  path: /
  defaults: { _controller: HikingBundle:Hiking:showTracks }

all_tracks:
  path: /tracks
  defaults: { _controller: HikingBundle:Hiking:showTracks }

single_track:
  path: /track/{track_id}
  defaults: { _controller: HikingBundle:Hiking:showSingleTrack }
  requirements:
    track_id: \d+

single_member:
  path: /member/{member_id}
  defaults: { _controller: HikingBundle:Hiking:showSingleMember }
  requirements:
    member_id: \d+

add_track:
  path: /admin/add_track
  defaults: { _controller: HikingBundle:AdminHiking:addTrackForm }

add_member:
  path: /admin/add_member
  defaults: { _controller:HikingBundle:AdminHiking:addMemberForm }

add_members_to_track:
  path: /admin/add_members/{track_id}
  defaults: { _controller:HikingBundle:AdminHiking:addMembersToTrack }
  requirements:
    member_id: \d+